language: python
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install tox-travis coveralls
script:
- tox
after_success:
- coveralls
deploy:
  provider: pypi
  user: SimionBaws
  password:
    secure: cw9bkYt6WQGX1zVbzIS08O3W7WxXSsCcAacf/m/3dGTb/sFMQj4AyCbjggnr3PT403Z2HHbKAXlDi64oohKdsrgW7CPUKDuOAVPssKttt499YhGSnT4lypsYL8SAY9Xc8ahpMf8+grHycbDIm0r0AOuPunJ7rZhRQ3vU85OZCarm3hE1gbymtGFZAKbgvV/VhwlMJic1FckoNAlLG5ZcRPq2W+K4kjcMqbEOCtuEkDVE37EI79uICiyWOnW8phltD68f8Gsg2HA2VKfcdynZWzP8ZcUp2Kehk9rrpTkQOHWG0JRuVUxQjXy05Sur+uzeT/NNwQqnw/JMsQnRJl+dk4bOx6cR04p7EqmuYUnRwhQDp1TgJfLirjQaui+7Wq9MwEV2xdrf/R0Tg/3J651iC1YRymgqc/Cs1X9k9l9W1tp5KrWevwLJIf+dL0jsryF5hBF0KmrJXu6pNlXfB11v/NgNUgqbBqzzUrSt/iarL9ecKjHCVqV8+CaVvdTK0c9/pXPxdh6FyxTcb9FslzzI6+zRF8y7Shp/HyI5dTwoxJXORBs7mJKHPsTxQdCb/ybxm37QAw7mUmyd2oMpGVlJkEFeywtX+TpqE5v90brExQphglOeLun4+k07yR0nc/cGsAcAjHMzPs5FK+AbbWcCEOjwOS2o0tjXJ8cqvA8dSvE=
  distributions: sdist bdist_wheel
  on:
    python: '3.6'
    branch: master
    tags: true
